package rules;

import model.Card;
import model.Room;
import model.Suspect;
import model.Weapon;
import model.TripleList;
import model.Triple;


rule "count matches"
	when
		$suspect:Suspect(  )
		$weapon:Weapon(  )
		$room:Room(  )
		$list:TripleList( )
		Number( $count : intValue ) from accumulate( $triple:Triple( suspect==$suspect || weapon==$weapon || room==$room) from $list, count($triple))
	then
		System.out.println($count);
end